``` mermaid
sequenceDiagram
    participant user
    participant browser
    participant server

    user->>browser: Enters a note and press submit
    activate browser
    browser->>server: POST https://studies.cs.helsinki.fi/exampleapp/new_note_spa
    activate server
    server-->>browser: Status code 201 Created with entered content object
    deactivate server
    browser->>browser: JavaScript updates the DOM
    deactivate browser
```
