``` mermaid

---
title: Single page app diagram
---

stateDiagram-v2
    User --> Browser: 1.enters /spa
    Browser --> Server: 2.HTTP GET request
    Server --> Browser: 3.returns HTML, CSS, JS
    Browser --> User: 4.renders initial page
    %% Then browser makes request to fetch the JSON data
    Browser --> Server: 5.HTTP GET data.json
    Server --> Browser: 6.returns JSON data
    Browser --> User: 7.receives updated view with data

     Note right of Browser: Browser processes server response and renders the initial page before data is loaded
     Note right of User: After completing the initial page rendering, the browser fetches the JSON data
```